# Site settings
title: Instant Roofing Prices
email: info@instantroofingprices.com
description: Get instant quotes for your roofing project. Fast, reliable estimates for roof repairs, replacements, and installations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

