# Site settings
title: Instant Roofing Prices
email: info@instantroofingprices.com
description: Get instant quotes for your roofing project. Fast, reliable estimates for roof repairs, replacements, and installations.
baseurl: "/roofing-lead-site" # the subpath of your site - IMPORTANT: match your repository name
url: "https://tim-amredev.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
